language: bash

services:
- docker

env:
  matrix:
  - ALPINE_VER=3.11 PYTHON_VERSION=3.7 TAGS=3.7,3,latest
  - ALPINE_VER=3.11 PYTHON_VERSION=3.6.5 TAGS=3.6

script:
- make 

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - charlessoft@qq.com
    on_success: never
    on_failure: always
