language: bash

services:
- docker

env:
  matrix:
  - ALPINE_VER=3.11.2 PYTHON_VER=3.6.5 TAGS=3.6,3,latest
  - ALPINE_VER=3.10.3 PYTHON_VER=3.6.5 TAGS=3.6

script:
- make 

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - charlessoft@qq.com
    on_success: never
    on_failure: always
